Feature/game
Sylcab74/thelag pull request #10
Opened 2018-12-13 16:22 UTC by tvililax

2018-12-13 16:59 UTC, JrBour requested changes

2018-12-13 16:59 UTC, JrBour commented on views/components/gamecard.blade.php
> +    <h2>{{ $game->name }}</h2>
Add alt attribute

2018-12-15 14:35 UTC, Sylcab74 approved these changes

2018-12-15 14:45 UTC, JrBour approved these changes
Nice

2018-12-15 14:45 UTC, merged